services:
  proxy:
    image: ghcr.io/openrings/skebob-proxy:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.proxy
    restart: unless-stopped

  backend:
    image: ghcr.io/openrings/skebob-backend:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.backend
    restart: unless-stopped

  prometheus:
    image: ghcr.io/openrings/skebob-prometheus:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus:/prometheus

  minecraft:
    image: ghcr.io/openrings/skebob-minecraft:latest
    build:
      dockerfile: ./docker/Dockerfile.prod.minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - target: 7777
        published: 7777
        protocol: tcp
      - target: 7777
        published: 7777
        protocol: udp
    environment:
      EULA: TRUE
      TYPE: PAPER
      VERSION: 1.21.1
      MEMORY: 6G
      MOTD: Памидоры памидоры помидоры
      DIFFICULTY: hard
      MAX_PLAYERS: 10000
      SNOOPER_ENABLED: false
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 24
      MODE: survival
      ONLINE_MODE: false
      SERVER_PORT: 7777
      SIMULATION_DISTANCE: 12
    volumes:
      - ./data/minecraft:/data

  database:
    image: mariadb:11.8
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: minecraft
    volumes:
      - ./data/database:/var/lib/mysql
