services:
  proxy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./docker/Caddyfile.dev:/etc/caddy/Caddyfile

  backend:
    build:
      dockerfile: ./docker/Dockerfile.dev.backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - cargo-cache:/usr/local/cargo

  frontend:
    build:
      dockerfile: ../docker/Dockerfile.dev.frontend
      context: ./frontend
    restart: always
    volumes:
      - ./frontend:/app

  grafana:
    image: grafana/grafana:12.0.2
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./docker/grafana:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:v3.4.2
    restart: always
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus

  minecraft:
    build:
      dockerfile: ../docker/Dockerfile.minecraft
      context: ./minecraft
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7777:7777
    environment:
      EULA: TRUE
      TYPE: PAPER
      VERSION: 1.21.1
      MEMORY: 1G
      MOTD: Памидоры памидоры помидоры
      DIFFICULTY: hard
      MAX_PLAYERS: 10000
      SNOOPER_ENABLED: false
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 64
      MODE: survival
      ONLINE_MODE: false
      SERVER_PORT: 7777
      SIMULATION_DISTANCE: 12
    volumes:
      - ./data/minecraft:/data

  database:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: minecraft
    volumes:
      - ./data/database:/var/lib/mysql

volumes:
  cargo-cache:
